spring:
  application:
    name: kis-stock-llm-analysis

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      group-id: stock-analysis-group
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: manual

  datasource:
    url: jdbc:mysql://localhost:3306/stock_analysis?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
# KIS API ??
kis:
  api:
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ${KIS_APP_KEY}
    app-secret: ${KIS_APP_SECRET}
    request:
      connect-timeout: 5000
      read-timeout: 10000

# LLM API ??
llm:
  # claude ?? gpt ??
  provider: gpt

  # Claude API
  claude:
    api-key: ${CLAUDE_API_KEY}
    model: claude-3-5-sonnet-20241022
    max-tokens: 2000

  # OpenAI API
  gpt:
    api-key: ${OPENAI_API_KEY}
    model: gpt-4o-mini
    max-tokens: 2000


# ?? ??
analysis:
  top-stocks: 10
  days-back: 60

logging:
  level:
    root: INFO
    com.stock: DEBUG